export const GET_POSTS_REQUEST_START = 'GET_POSTS_REQUEST_START'
export const SET_POSTS = 'SET_POSTS'
export const GET_POSTS_REQUEST_FAILED = 'GET_POSTS_REQUEST_FAILED'


export const GET_POST_REQUEST_START = 'GET_POST_REQUEST_START'
export const SET_POST = "SET_POST"
export const GET_POST_REQUEST_FAILED = 'GET_POST_REQUEST_FAILED'

export const GET_COMMENTS_REQUEST_START = 'GET_COMMENTS_REQUEST_START'
export const SET_COMMENTS = 'SET_COMMENTS'
export const GET_COMMENTS_REQUEST_FAILED = 'GET_COMMENTS_REQUEST_FAILED'

